CREATE TABLE STUDENTS_DEVOPS (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    firstname VARCHAR(30) NOT NULL,
    lastname VARCHAR(30) NOT NULL
);

INSERT INTO STUDENTS_DEVOPS(firstname,lastname) VALUES('Student','1');
INSERT INTO STUDENTS_DEVOPS(firstname,lastname) VALUES('Student','2');
